[env:esp32dev]
platform = espressif32 @ 6.9.0
board = esp32dev ; Đổi tên board ở đây nếu bạn dùng loại khác
framework = arduino

; Tốc độ Serial Monitor
monitor_speed = 115200

; Các cấu hình để tránh lỗi tràn bộ nhớ khi dùng WebServer
board_build.partitions = huge_app.csv

; Danh sách thư viện cần thiết tự động tải về
lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2